version: '2.1'

services:
  db:
    image: cassandra:3.11.5
    ports:
      - 9042:9042
      - 7199:7199
      - 7000:7000
      - 7001:7001
    environment:
      - CASSANDRA_CLUSTER_NAME='K8Demo'
    restart: always
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 5

  micronaut:
    build: ./
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
